### ISSUE TITLE
Missing toleration for Prometheus push-gateway pod ?

### ISSUE THREAD

**Issue by raphaelpoumarede** [sassoftware/viya4-monitoring-kubernetes#4]
In my AKS deployment, there is no available node for the push-gateway pod. 
Unlike the other prometheus/grafana pods, the "push-gateway" pod does not have a toleration for the "stateful" node. 
As the result the pod remains pending.
When I add this in my $USER_DIR/monitoring/user-values-pushgateway.yaml  :
```yaml
tolerations:
  - effect: NoSchedule
    key: workload.sas.com/class
    value: stateful
```
it solves the issue.
Thanks
